usuario = input('Digite seu nome: ')
idade = input('Digite sua idade: ')
pais = input('Digite seu país: ')
estado = input('Digite seu estado: ')
cidade = input('Digite sua cidade: ')
bairro = input('Digite seu bairro: ')
cep = int(input('Digite o seu CEP: '))
rua = input('Digite o nome de sua rua: ')
numero_predio = int(input('Digite o número do seu prédio: '))
numero_apartamento = int(input('Digite o número do seu apartamento: '))
print(f'{usuario} você tem {idade} anos. Você mora no {pais}, no Estado de {estado}, na cidade de {cidade}, no bairro {bairro}, na rua {rua}, número {numero_predio}, no apartamento {numero_apartamento}.Seu CEP é: {cep}')
